/* eslint-disable testing-library/no-render-in-setup */

import { Maze } from 'components/maze/index'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MazeContext, MazeContextProvider } from 'context/maze/context'
import { MazeData } from 'context/maze'

const mockMazeData = {
  pony: [65],
  domokun: [70],
  'end-point': [218],
  size: [15, 15],
  difficulty: 1,
  data: [
    ['west', 'north'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['north'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['north'],
    ['north'],
    ['north'],
    ['north'],
    ['west', 'north'],
    [],
    ['west', 'north'],
    ['north'],
    [],
    ['west'],
    ['west', 'north'],
    ['north'],
    ['west'],
    [],
    ['west'],
    ['north'],
    ['north'],
    ['west', 'north'],
    ['west'],
    ['west'],
    ['north'],
    ['west'],
    ['north'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['north'],
    ['north'],
    ['north'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['west', 'north'],
    ['west'],
    ['north'],
    ['north'],
    ['west'],
    [],
    ['west', 'north'],
    [],
    ['west', 'north'],
    ['north'],
    ['north'],
    ['north'],
    [],
    ['west'],
    ['west'],
    ['west'],
    ['west', 'north'],
    ['north'],
    [],
    ['west'],
    ['north'],
    [],
    ['west'],
    ['west'],
    ['north'],
    ['west'],
    ['west', 'north'],
    ['north'],
    ['west'],
    [],
    ['west'],
    ['west'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['north'],
    ['north'],
    ['west'],
    ['west', 'north'],
    [],
    ['west', 'north'],
    [],
    ['west'],
    ['north'],
    ['west'],
    ['west'],
    ['west', 'north'],
    [],
    ['west'],
    ['west', 'north'],
    ['north'],
    ['west'],
    [],
    ['west'],
    ['north'],
    [],
    ['west', 'north'],
    ['north'],
    [],
    ['west'],
    ['west'],
    ['west'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['west'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['west'],
    ['west'],
    ['north'],
    ['west', 'north'],
    [],
    ['west'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['west'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['north'],
    ['north'],
    [],
    ['west'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['west', 'north'],
    [],
    ['west', 'north'],
    [],
    ['west'],
    ['west'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    ['west'],
    [],
    ['west', 'north'],
    ['west'],
    ['west', 'north'],
    [],
    ['west', 'north'],
    ['west'],
    [],
    ['west'],
    ['west', 'north'],
    [],
    ['west'],
    ['west'],
    ['north'],
    ['north'],
    ['north'],
    [],
    [],
    ['west'],
    ['north'],
    [],
    ['north'],
    ['west', 'north'],
    [],
    ['west'],
    ['north'],
    [],
    ['west'],
    ['north'],
    ['north'],
    ['west', 'north'],
    ['north'],
    ['north'],
    ['north'],
    ['west'],
    ['west', 'north'],
    ['north'],
    ['west'],
    ['north'],
    ['north'],
    ['west'],
    ['west', 'north'],
    ['west', 'north'],
    ['north'],
    ['west'],
    ['west', 'north'],
    ['north'],
    ['west'],
    ['north'],
    [],
    ['west'],
    ['west'],
    ['north'],
    ['west'],
    ['west'],
    ['west'],
    [],
    ['west'],
    ['west'],
    [],
    [],
    ['west'],
    ['north'],
    ['north'],
    ['north'],
    [],
    ['west', 'north'],
    [],
    ['north'],
    [],
    ['west', 'north'],
    [],
  ],
  maze_id: 'baa94006-ac4e-4002-b418-3a0904389b1d',
  'game-state': {
    state: 'Active',
    'state-result': 'Successfully created',
  },
}

describe('<Maze />', () => {
  beforeEach(() => {
    render(
      <MazeContext.Provider
        value={{ mazeData: mockMazeData as MazeData, dispatch: () => null }}
      >
        <Maze />
      </MazeContext.Provider>
    )
  })

  it('Should have a maze with 15 rows and 15 cells in each row', () => {
    const rows = screen.getByTestId('maze').childNodes
    const cells = rows[0].childNodes

    expect(rows.length).toBe(15)
    expect(cells.length).toBe(15)
  })

  it('Should have a pony, a domokun and exit in maze', () => {
    expect(screen.getByAltText('domokun')).toBeInTheDocument()
    expect(screen.getByAltText('pony')).toBeInTheDocument()
    expect(screen.getByAltText('exit')).toBeInTheDocument()
  })
})
